### PR TITLE
Prune networks and containers before initialization

### PR DESCRIPTION
**Pull request by gterzian**
FIX https://github.com/massalabs/massa-network-simulator/issues/41

### CODE REVIEW

**Comment by gterzian** [comment]
@AurelienFT When I remove it I get an error when the first argument is used:

```
tbf: illegal value for "rate": "kbit"
Illegal "latency"
```

which would seem to indicate that `UL_KBITPS` is empty. 

Do I need to do something specific to pass those two arguments to the script? 

What I am doing is only building the docker image, and the only change I make is to `ARG GIT_BRANCH`.

**Comment by AurelienFT** [comment]
> Do I need to do something specific to pass those two arguments to the script?

This arguments should be filed by the main.py that pass to environment variables this values.

**Comment by sydhds** [comment]
Just a quick look and I think that the GIT BRANCH should not be modified ?

**Comment by gterzian** [comment]
> Just a quick look and I think that the GIT BRANCH should not be modified ?

The branch needs to be modified in order to run the simulator with the changes that are to be tested(as opposed to using `main`).

**Comment by gterzian** [comment]
@AurelienFT @sydhds So I think the shift error occured only because I was manually starting the container. 

Now, looking at `main.py`, I think there is a missing call to `DockerWrapper.create_container`. 

Currently we immediately do `create_network`, and it fails locally with the below:

```
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
Initializing...
Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1245, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1291, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1240, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 948, in send
    self.connect()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1245, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1291, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1240, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 948, in send
    self.connect()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 52, in main
    container_wrapper = ContainerWrapper()
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 12, in __init__
    self.docker_client = docker.from_env()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
Initializing...
Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http+docker://localhost/v1.41/networks/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 53, in main
    network = container_wrapper.create_network(
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 16, in create_network
    return NetworkWrapper(self, subnet, gateway_ip)
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 34, in __init__
    self.network = self.wrapper.docker_client.networks.create(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/models/networks.py", line 156, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/network.py", line 153, in create_network
    return self._result(res, json=True)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 403 Client Error for http+docker://localhost/v1.41/networks/create: Forbidden ("Pool overlaps with other one on this address space")
/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py:57: UserWarning: failed removing network None: 'NetworkWrapper' object has no attribute 'network'
  warnings.warn("failed removing network {}: {}".format(self.id, e))
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
Initializing...
Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/networks/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 53, in main
    network = container_wrapper.create_network(
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 16, in create_network
    return NetworkWrapper(self, subnet, gateway_ip)
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 34, in __init__
    self.network = self.wrapper.docker_client.networks.create(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/models/networks.py", line 156, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/network.py", line 153, in create_network
    return self._result(res, json=True)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/networks/create: Internal Server Error ("invalid gateway address 192.168.65.0.254 in Ipam configuration")
/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py:57: UserWarning: failed removing network None: 'NetworkWrapper' object has no attribute 'network'
  warnings.warn("failed removing network {}: {}".format(self.id, e))
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
Initializing...
Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/networks/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 53, in main
    network = container_wrapper.create_network(
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 16, in create_network
    return NetworkWrapper(self, subnet, gateway_ip)
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 34, in __init__
    self.network = self.wrapper.docker_client.networks.create(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/models/networks.py", line 156, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/network.py", line 153, in create_network
    return self._result(res, json=True)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/networks/create: Internal Server Error ("invalid gateway address 192.168.65.0.254 in Ipam configuration")
/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py:57: UserWarning: failed removing network None: 'NetworkWrapper' object has no attribute 'network'
  warnings.warn("failed removing network {}: {}".format(self.id, e))
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
[]
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
[<Image: 'massa-simulator:latest'>]
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/004c6664bd7aaa50f054c7d5bca4ac917d4a71b73f015f2641170774ab20f9d7/start

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main()
  File "main.py", line 53, in main
    client.containers.run("ubuntu", "massa-simulator:latest")
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/models/containers.py", line 853, in run
    container.start()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/container.py", line 1121, in start
    self._raise_for_status(res)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/004c6664bd7aaa50f054c7d5bca4ac917d4a71b73f015f2641170774ab20f9d7/start: Bad Request ("failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "massa-simulator:latest": executable file not found in $PATH: unknown")
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ 
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
[<Container: b91ffb2cebd9>]
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
Initializing...
Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http+docker://localhost/v1.41/networks/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 53, in main
    network = container_wrapper.create_network(
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 16, in create_network
    return NetworkWrapper(self, subnet, gateway_ip)
  File "/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py", line 34, in __init__
    self.network = self.wrapper.docker_client.networks.create(
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/models/networks.py", line 156, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/network.py", line 153, in create_network
    return self._result(res, json=True)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 403 Client Error for http+docker://localhost/v1.41/networks/create: Forbidden ("Pool overlaps with other one on this address space")
/Users/Gregory/Projects/massa-network-simulator/docker_wrapper.py:57: UserWarning: failed removing network None: 'NetworkWrapper' object has no attribute 'network'
  warnings.warn("failed removing network {}: {}".format(self.id, e))

```

**Comment by AurelienFT** [comment]
Never seen this :o

**Comment by gterzian** [comment]
Ok the latest changes fix the problem for me, I can now successfully run `main.py`. 

From https://github.com/maxking/docker-mailman/issues/85#issuecomment-349429246

@AurelienFT ready for review

**Comment by AurelienFT** [comment]
Lets goooooo !!!!!

**Pull request merged**
